name: ${PROJECT_NAME:-your-project-name}

services:
    joomla:
        image: joomla:${JOOMLA_VERSION:-5.2-php8.3-apache}
        container_name: ${CONTAINER_PREFIX:-joomla}-app
        restart: always
        ports:
            - ${WEB_PORT:-6969}:80
        environment:
            - APACHE_RUN_GROUP=#1000
            - APACHE_RUN_USER=#1000
            - JOOMLA_DB_HOST=joomladb
            - JOOMLA_DB_NAME=${DB_NAME:-joomla}
            - JOOMLA_DB_PASSWORD=${DB_PASSWORD:-examplepass}
            - JOOMLA_DB_USER=${DB_USER:-joomla}
            - JOOMLA_SITE_NAME=${JOOMLA_SITE_NAME:-Joomla}
            - JOOMLA_ADMIN_USER=${JOOMLA_ADMIN_USER:-Joomla Hero}
            - JOOMLA_ADMIN_USERNAME=${JOOMLA_ADMIN_USERNAME:-joomla}
            - JOOMLA_ADMIN_PASSWORD=${JOOMLA_ADMIN_PASSWORD:-joomla@secured}
            - JOOMLA_ADMIN_EMAIL=${JOOMLA_ADMIN_EMAIL:-joomla@example.com}
        depends_on:
            joomladb:
                condition: service_healthy
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./joomla:/var/www/html
        networks:
            - joomla_network

    joomladb:
        image: mysql:${MYSQL_VERSION:-latest}
        container_name: ${CONTAINER_PREFIX:-joomla}-db
        restart: always
        ports:
            - ${MYSQL_PORT:-3306}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=joomla
            - MYSQL_USER=${DB_USER:-joomla}
            - MYSQL_PASSWORD=${DB_PASSWORD:-examplepass}
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - joomla_network

    phpmyadmin:
        image: 'phpmyadmin:${PHPMYADMIN_VERSION:-latest}'
        container_name: ${CONTAINER_PREFIX:-joomla}-phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=joomladb
        networks:
            - joomla_network

    mailhog:
        image: mailhog/mailhog:${MAILHOG_VERSION:-latest}
        container_name: ${CONTAINER_PREFIX:-joomla}-mailhog
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - joomla_network

networks:
    joomla_network:
